In [2]:
import pandas as pd
from math import *

with open('/Users/k.sakamoto/Desktop/log/target_posision.txt', mode='r') as f:
    lines = [s.strip() for s in f.readlines()]
    target = (float(lines[0]), float(lines[1]))

df = pd.read_csv('/Users/k.sakamoto/Desktop/log/phase6.csv')
for i in range(len(df)):
    df.iloc[i, 3] = df.iloc[i, 3] * 180 / pi

df

     time_stamp   latitude   longitude       theta    distance
0    184.022204  39.880560  139.850468  140.405178  130.208952
1    184.497543  39.880560  139.850468  111.299575  130.208952
2    185.476796  39.880560  139.850468  197.474067  130.208952
3    186.032218  39.880560  139.850468  179.014924  130.208952
4    194.272196  39.880567  139.850442  139.113609  127.921955
..          ...        ...         ...         ...         ...
119  451.643112  39.880773  139.849023  189.680998   11.033711
120  452.484920  39.880773  139.849023  132.343035   11.033711
121  454.910381  39.880777  139.849017  131.775520   10.376859
122  457.220885  39.880783  139.849010  244.927872    9.498942
123  459.016843  39.880783  139.849010  128.830125    9.498942

[124 rows x 5 columns]

In [3]:
print(2.917037123265491 * 180 / pi)

167.1339158460955